### PR TITLE
Improve NERSC login header

### PR DESCRIPTION
**Pull request by EiffL**
This PR puts the JS files provided by NEWT in the assets folder, which allows us to change the look of the login banner. I've changed it a little bit to look better, using bootstrap elements.
Another strategy would be to find a way to update the `topAuth` element after it gets added by the newt js, but that's a bit risky, it can break some connections.
Or updating the bootstrap version as suggested in #37

### CODE REVIEW

**Comment by kadrlica** [comment]
Thanks @EiffL. I was actually planning to go the other direction on this (a la issue #37). The NEWT header has problems with the old version of bootstrap that we have in assets (2.3.2), but looks fine with bootstrap v3.0+.  You can see an example of what NEWT should look like here: https://portal-auth.nersc.gov/projecta/lsst/dev-exp-checker/newt.html

Given this, do you think it's a good idea to proceed with your update here?

**Comment by kadrlica** [comment]
I spent a few hours trying to update Bootstrap and hit some issues, so maybe this is the best way in the interim? I'm not an expert on this, so your thoughts/advice is greatly appreciated.

**Comment by EiffL** [comment]
I don't like the solution in this PR too much because it could break whenever NERSC decides to update NEWT. Updating bootstrap is probably a much better idea, I gave it a try but everything started breaking, so I felt that it might still be a useful fix for now...

**Comment by EiffL** [comment]
Thanks @kadrlica just let me know if if breaks for any reasons.

**Comment by kadrlica** [comment]
Thank you! I'm hoping that we won't need to support it for too long before we get the bootstrap update in place.

**Comment by kadrlica** [comment]
@EiffL I was talking to people at NERSC about fixing this in newt.js. Can you provide any advice on your fix? I imagine there was some naming conflict that existed in Bootsrap v2 but went away in v3?

**Comment by kadrlica** [comment]
@agreiner here's the bootstrap issue.

**Comment by EiffL** [comment]
Right, so the thing that wasn't working apparently with bootstrap was the form class, in the official newt.js, it  is `<form method=POST style='display:inline; ...>` I'm guessing the CSS defaults for bootstrap are interfering with the style specified here. I replaced that by: `<form class="form-inline" method=POST style='display:inline;' ....>` (although I don't think the style matters here) "form-inline" is the bootstrap class for inline forms, then it looks good.
I've also tweaked a little bit the look of it so that it would fit on one line with the same width as the main exposure checker container.

**Pull request merged**
